// This file is autogenerated. Changes will be overwritten.
#include "JWPBFA34E2/moc_OpenGlVideoQtQuick.cpp"
#include "JWPBFA34E2/moc_QFFmpegGLWidget.cpp"
#include "JWPBFA34E2/moc_VideoProducer.cpp"
#include "JWPBFA34E2/moc_XVideoWidget.cpp"
#include "JWPBFA34E2/moc_mainwindow.cpp"
