// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_OpenGlVideoQtQuick.cpp"
#include "EWIEGA46WW/moc_QFFmpegGLWidget.cpp"
#include "EWIEGA46WW/moc_VideoProducer.cpp"
#include "EWIEGA46WW/moc_XVideoWidget.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
