#include "PixelFormats.h"

//Generated by converter.py

StaticPixelFormats PixelFormats::staticPixelFormats;

Fraction zero  = {0,1};
Fraction one   = {1,1};
Fraction two   = {1,2};
Fraction three = {1,3};
Fraction four  = {1,4};

StaticPixelFormats::StaticPixelFormats() {

    pixelFormats[AV_PIX_FMT_YUV420P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVJ420P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUVJ,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV422P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVJ422P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUVJ,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV444P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVJ444P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUVJ,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_GRAY8] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        GRAY,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_UYVY422] = PixelFormat {
        //Fraction yuvSizes[3];
        {four,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        UYVY,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUYV422] = PixelFormat {
        //Fraction yuvSizes[3];
        {four,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        YUYV,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_BGR24] = PixelFormat {
        //Fraction yuvSizes[3];
        {three,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_RGB8,GL_RGB8,GL_RGB8},
        //GLenum yuvGlFormat[3];
        {GL_BGR,GL_BGR,GL_BGR},
        //int textureFormat
        BGR,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_RGB24] = PixelFormat {
        //Fraction yuvSizes[3];
        {three,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_RGB8,GL_RGB8,GL_RGB8},
        //GLenum yuvGlFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_MONOWHITE] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_RGB8,GL_RGB8,GL_RGB8},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_MONOBLACK] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_RGB8,GL_RGB8,GL_RGB8},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_PAL8] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_BGR8] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //GLenum yuvGlFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //int textureFormat
        BGR8,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE_2_3_3_REV
    };
    pixelFormats[AV_PIX_FMT_RGB8] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //GLenum yuvGlFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //int textureFormat
        BGR8,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE_3_3_2
    };
    pixelFormats[AV_PIX_FMT_BGR4] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE4,GL_LUMINANCE4,GL_LUMINANCE4},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        BGR4,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_NV12] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,two,zero},
        //Fraction yuvWidths[3];
        {one,two,zero},
        //Fraction yuvHeights[3];
        {one,two,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE_ALPHA,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE_ALPHA,GL_LUMINANCE},
        //int textureFormat
        NV12,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_NV21] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,two,zero},
        //Fraction yuvWidths[3];
        {one,two,zero},
        //Fraction yuvHeights[3];
        {one,two,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE_ALPHA,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE_ALPHA,GL_LUMINANCE},
        //int textureFormat
        NV21,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV420P10LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //int textureFormat
        YUV420P10LE,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV422P10LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //int textureFormat
        YUV420P10LE,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV444P10LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //int textureFormat
        YUV420P10LE,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVA420P10LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //int textureFormat
        YUV420P10LE,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVA422P10LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //int textureFormat
        YUV420P10LE,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVA444P10LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //int textureFormat
        YUV420P10LE,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV410P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,four,four},
        //Fraction yuvHeights[3];
        {one,four,four},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUV411P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_ARGB] = PixelFormat {
        //Fraction yuvSizes[3];
        {four,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        ARGB,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_RGBA] = PixelFormat {
        //Fraction yuvSizes[3];
        {four,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        RGBA,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_ABGR] = PixelFormat {
        //Fraction yuvSizes[3];
        {four,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        ABGR,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_BGRA] = PixelFormat {
        //Fraction yuvSizes[3];
        {four,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        BGRA,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_GRAY16BE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        GRAY,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_GRAY16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        GRAY,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUV440P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,one,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVJ440P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,one,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUVJ,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_YUVA420P] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,one,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_UYYVYY411] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        UYYVYY,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_RGB444LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        RGB444,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_SHORT_4_4_4_4
    };
    pixelFormats[AV_PIX_FMT_RGB444BE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        RGB444,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_SHORT_4_4_4_4
    };
    pixelFormats[AV_PIX_FMT_BGR444LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        BGR444,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_SHORT_4_4_4_4
    };
    pixelFormats[AV_PIX_FMT_BGR444BE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //GLenum yuvGlFormat[3];
        {GL_RGBA,GL_RGBA,GL_RGBA},
        //int textureFormat
        BGR444,
        //bool isPlanar
        false,
        //GLenum dataType
        GL_UNSIGNED_SHORT_4_4_4_4
    };
    pixelFormats[AV_PIX_FMT_YUV420P16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV16,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUV420P16BE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV16,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUV422P16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV16,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUV422P16BE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV16,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUV444P16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV16,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUV444P16BE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV16,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUVA420P16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUVA422P16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_YUVA444P16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,two,two},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BAYER_BGGR16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        BGGR,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BAYER_RGGB16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        RGGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BAYER_GBRG16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        GBRG,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BAYER_GRBG16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        GRBG,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BAYER_GRBG16LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,one,one},
        //Fraction yuvWidths[3];
        {one,one,one},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        GRBG,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_RGB565LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //GLenum yuvGlFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT_5_6_5
    };
    pixelFormats[AV_PIX_FMT_RGB555LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_BGRA,GL_BGRA,GL_BGRA},
        //GLenum yuvGlFormat[3];
        {GL_BGRA,GL_BGRA,GL_BGRA},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT_1_5_5_5_REV
    };
    pixelFormats[AV_PIX_FMT_BGR565LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //GLenum yuvGlFormat[3];
        {GL_RGB,GL_RGB,GL_RGB},
        //int textureFormat
        BGR565,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT_5_6_5
    };
    pixelFormats[AV_PIX_FMT_RGB555LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_BGRA,GL_BGRA,GL_BGRA},
        //GLenum yuvGlFormat[3];
        {GL_BGRA,GL_BGRA,GL_BGRA},
        //int textureFormat
        BGR565,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT_1_5_5_5_REV
    };
    pixelFormats[AV_PIX_FMT_RGB48LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BGR48LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE16,GL_LUMINANCE16,GL_LUMINANCE16},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        BGR,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_RGBA64LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        RGB,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_BGRA64LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {two,zero,zero},
        //Fraction yuvWidths[3];
        {one,zero,zero},
        //Fraction yuvHeights[3];
        {one,zero,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA,GL_LUMINANCE_ALPHA},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        BGR,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_SHORT
    };
    pixelFormats[AV_PIX_FMT_NV16] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,one,one},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_NV20LE] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,one,one},
        //Fraction yuvWidths[3];
        {one,two,two},
        //Fraction yuvHeights[3];
        {one,two,two},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE,GL_LUMINANCE},
        //int textureFormat
        YUV,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
    pixelFormats[AV_PIX_FMT_DXVA2_VLD] = PixelFormat {
        //Fraction yuvSizes[3];
        {one,two,zero},
        //Fraction yuvWidths[3];
        {one,two,zero},
        //Fraction yuvHeights[3];
        {one,two,zero},
        //GLint yuvInternalFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE_ALPHA,GL_LUMINANCE},
        //GLenum yuvGlFormat[3];
        {GL_LUMINANCE,GL_LUMINANCE_ALPHA,GL_LUMINANCE},
        //int textureFormat
        NV12,
        //bool isPlanar
        true,
        //GLenum dataType
        GL_UNSIGNED_BYTE
    };
}